### ISSUE TITLE
Review and Issues

### ISSUE THREAD

**Issue by geetika-kathuria** [PreethiPrasad16/DragatronAssignment#1]
1. Please make the datefield editable.
2. Description field placeholder says maxlength is 50 whereas it lets only add 10 characters.
3. It loses data on refresh; persist the data for the session.
4. Price field is taking negative values.
5. Add a capability to search via other fields too.
6. On editing, the image isn't available for edition.

**Comment by PreethiPrasad16** [comment]
I have edited my code and have committed the changes, kindly review it.
